// Known skills and terms with RU/EN synonyms. The first alias is the display
// label; every alias counts as the same skill when matching vacancy ↔ resume.
// Unknown terms are still picked up by the fallback extractor in engine.ts —
// this list only improves matching across languages and spelling variants.

export type TermCategory = 'tool' | 'hard' | 'domain' | 'soft';

export interface LexiconEntry {
  id: string;
  cat: TermCategory;
  aliases: string[];
}

const e = (cat: TermCategory, ...aliases: string[]): LexiconEntry => ({
  id: aliases[0].toLowerCase(),
  cat,
  aliases,
});

export const lexicon: LexiconEntry[] = [
  // --- marketing & growth ---
  e('hard', 'GTM', 'go-to-market', 'go to market', 'вывод на рынок', 'вывод продукта на рынок'),
  e('hard', 'Performance marketing', 'performance-маркетинг', 'перформанс-маркетинг', 'перформанс маркетинг', 'performance'),
  e('hard', 'Digital marketing', 'digital-маркетинг', 'диджитал-маркетинг', 'интернет-маркетинг', 'цифровой маркетинг'),
  e('hard', 'Product marketing', 'продуктовый маркетинг', 'product marketing manager'),
  e('hard', 'Growth marketing', 'growth', 'growth hacking', 'маркетинг роста', 'рост продукта'),
  e('hard', 'B2B marketing', 'b2b-маркетинг', 'b2b маркетинг'),
  e('hard', 'Brand marketing', 'бренд-маркетинг', 'брендинг', 'branding', 'бренд'),
  e('hard', 'Content marketing', 'контент-маркетинг', 'контент маркетинг', 'контент'),
  e('hard', 'SEO', 'поисковая оптимизация', 'search engine optimization'),
  e('hard', 'SEM', 'контекстная реклама', 'контекст', 'paid search', 'ppc', 'search ads'),
  e('hard', 'Programmatic', 'программатик', 'programmatic buying', 'rtb'),
  e('hard', 'Media buying', 'закупка медиа', 'медиабаинг', 'закупка трафика', 'медийная реклама', 'display'),
  e('hard', 'Targeted ads', 'таргетированная реклама', 'таргет', 'таргетинг', 'paid social'),
  e('hard', 'Email marketing', 'email-маркетинг', 'email маркетинг', 'e-mail маркетинг', 'рассылки', 'email'),
  e('hard', 'CRM marketing', 'crm-маркетинг', 'crm маркетинг', 'cvm', 'customer value management', 'lifecycle marketing', 'lifecycle'),
  e('hard', 'Retention', 'удержание', 'удержание клиентов', 'retention marketing', 'возвращение клиентов'),
  e('hard', 'Lead generation', 'лидогенерация', 'генерация лидов', 'demand generation', 'demand gen'),
  e('hard', 'Pipeline', 'pipeline generation', 'воронка продаж', 'пайплайн'),
  e('hard', 'Positioning', 'позиционирование', 'messaging', 'ценностное предложение', 'value proposition'),
  e('hard', 'Market research', 'исследование рынка', 'исследования рынка', 'маркетинговые исследования', 'research'),
  e('hard', 'Customer discovery', 'кастдев', 'custdev', 'customer development', 'интервью с клиентами', 'customer interviews'),
  e('hard', 'Competitive analysis', 'конкурентный анализ', 'анализ конкурентов', 'competitor analysis'),
  e('hard', 'Pricing', 'ценообразование', 'монетизация', 'monetization', 'тарификация'),
  e('hard', 'PR', 'public relations', 'связи с общественностью', 'пиар'),
  e('hard', 'Events', 'ивенты', 'мероприятия', 'конференции', 'event marketing'),
  e('hard', 'Partnerships', 'партнёрства', 'партнерства', 'партнерский маркетинг', 'партнёрский маркетинг', 'partner marketing', 'affiliate'),
  e('hard', 'Influencer marketing', 'блогеры', 'инфлюенс-маркетинг', 'работа с блогерами'),
  e('hard', 'SMM', 'социальные сети', 'social media', 'соцсети'),
  e('hard', 'ABM', 'account-based marketing', 'account based marketing'),
  e('hard', 'Marketing automation', 'автоматизация маркетинга', 'маркетинговая автоматизация'),
  e('hard', 'Omnichannel', 'омниканальность', 'омниканальный', 'multi-channel', 'мультиканальный', 'мультиканальность'),
  e('hard', 'Marketing strategy', 'маркетинговая стратегия', 'стратегия маркетинга', 'стратегический маркетинг'),
  e('hard', 'Budget management', 'управление бюджетом', 'маркетинговый бюджет', 'бюджетирование', 'budgeting', 'budget planning', 'планирование бюджета'),
  e('hard', 'Marketing P&L', 'p&l', 'pnl', 'p&l маркетинга', 'отчёт о прибылях и убытках'),
  e('hard', 'Media planning', 'медиапланирование', 'медиаплан'),
  e('hard', 'Copywriting', 'копирайтинг', 'тексты'),
  e('hard', 'Landing pages', 'лендинги', 'лендинг', 'посадочные страницы', 'landing page'),
  e('hard', 'CRO', 'conversion rate optimization', 'оптимизация конверсии'),
  e('hard', 'Customer journey', 'cjm', 'customer journey map', 'путь клиента'),
  e('hard', 'Segmentation', 'сегментация', 'сегментирование'),
  e('hard', 'RFM', 'rfm-анализ', 'rfm анализ', 'rfm-сегментация'),
  e('hard', 'Loyalty programs', 'программа лояльности', 'программы лояльности', 'лояльность', 'loyalty'),
  e('hard', 'Personalization', 'персонализация'),
  e('hard', 'Marketplaces', 'маркетплейсы', 'маркетплейс', 'marketplace', 'ozon', 'wildberries'),
  e('hard', 'E-commerce', 'ecommerce', 'электронная коммерция', 'интернет-магазин', 'e-com', 'ecom'),
  e('hard', 'Retail media', 'ритейл-медиа', 'ритейл медиа'),
  e('hard', 'Trade marketing', 'трейд-маркетинг', 'трейд маркетинг'),
  e('hard', 'Digital shelf', 'цифровая полка', 'on-shelf availability', 'osa'),

  // --- metrics & analytics ---
  e('hard', 'CAC', 'стоимость привлечения клиента', 'customer acquisition cost'),
  e('hard', 'CPA', 'cost per action', 'стоимость целевого действия'),
  e('hard', 'CPL', 'стоимость лида', 'cost per lead'),
  e('hard', 'LTV', 'cltv', 'clv', 'lifetime value', 'пожизненная ценность клиента'),
  e('hard', 'ARPU', 'arppu', 'средний доход на пользователя'),
  e('hard', 'ROMI', 'roi', 'roas', 'drr', 'дрр', 'окупаемость маркетинга', 'окупаемость'),
  e('hard', 'Churn', 'отток', 'отток клиентов', 'churn rate'),
  e('hard', 'MRR', 'arr', 'recurring revenue', 'регулярная выручка'),
  e('hard', 'Conversion', 'конверсия', 'конверсии', 'cr', 'conversion rate'),
  e('hard', 'Unit economics', 'юнит-экономика', 'юнит экономика', 'unit-экономика', 'unit-economics'),
  e('hard', 'Funnel analysis', 'воронка', 'воронки', 'funnel', 'аналитика воронки'),
  e('hard', 'Cohort analysis', 'когортный анализ', 'когорты', 'cohorts'),
  e('hard', 'Attribution', 'атрибуция', 'модели атрибуции', 'attribution modeling'),
  e('hard', 'End-to-end analytics', 'сквозная аналитика', 'end to end analytics', 'e2e analytics'),
  e('hard', 'Marketing mix modeling', 'mmm', 'marketing mix model', 'медиамикс', 'маркетинг-микс'),
  e('hard', 'A/B testing', 'a/b-тесты', 'a/b тесты', 'аб-тесты', 'ab-тесты', 'a/b тестирование', 'ab testing', 'split testing', 'сплит-тесты', 'эксперименты', 'experiments', 'experimentation'),
  e('hard', 'Product analytics', 'продуктовая аналитика'),
  e('hard', 'Marketing analytics', 'маркетинговая аналитика', 'веб-аналитика', 'web analytics'),
  e('hard', 'Data analysis', 'анализ данных', 'data analytics', 'аналитика данных', 'аналитика', 'analytics'),
  e('hard', 'KPI', 'kpis', 'ключевые показатели', 'метрики', 'metrics', 'okr', 'okrs'),
  e('hard', 'Forecasting', 'прогнозирование', 'прогноз', 'forecast'),
  e('hard', 'Reporting', 'отчётность', 'отчетность', 'дашборды', 'dashboards', 'дашборд'),
  e('hard', 'Statistics', 'статистика', 'statistical analysis', 'матстатистика'),
  e('hard', 'Machine learning', 'ml', 'машинное обучение'),

  // --- product & management ---
  e('hard', 'Product management', 'управление продуктом', 'продакт-менеджмент', 'product manager'),
  e('hard', 'Product strategy', 'продуктовая стратегия', 'стратегия продукта'),
  e('hard', 'Roadmap', 'роадмап', 'дорожная карта', 'roadmapping'),
  e('hard', 'MVP', 'минимально жизнеспособный продукт', 'mlp'),
  e('hard', 'Product-market fit', 'pmf', 'product market fit'),
  e('hard', 'JTBD', 'jobs to be done', 'jobs-to-be-done'),
  e('hard', 'Hypothesis testing', 'проверка гипотез', 'гипотезы', 'тестирование гипотез', 'hypotheses'),
  e('hard', 'User research', 'исследования пользователей', 'ux research', 'ux-исследования'),
  e('hard', 'UX', 'user experience', 'ui/ux', 'ux/ui', 'пользовательский опыт'),
  e('hard', 'Agile', 'scrum', 'kanban', 'канбан', 'скрам', 'гибкие методологии'),
  e('hard', 'Project management', 'управление проектами', 'проектное управление'),
  e('hard', 'Team management', 'управление командой', 'руководство командой', 'team lead', 'people management', 'лидерство команды', 'управление командами'),
  e('hard', 'Hiring', 'найм', 'рекрутинг', 'подбор команды', 'recruiting', 'построение команды', 'team building'),
  e('hard', 'Strategy', 'стратегия', 'стратегическое планирование', 'strategic planning'),
  e('hard', 'Business development', 'развитие бизнеса', 'бизнес-девелопмент', 'bizdev', 'biz dev'),
  e('hard', 'Sales', 'продажи', 'b2b продажи', 'b2b-продажи', 'sales management', 'управление продажами'),
  e('hard', 'Key account management', 'kam', 'ключевые клиенты', 'работа с ключевыми клиентами', 'account management'),
  e('hard', 'Negotiations', 'переговоры', 'negotiation', 'ведение переговоров'),
  e('hard', 'Stakeholder management', 'работа со стейкхолдерами', 'стейкхолдеры', 'stakeholders'),
  e('hard', 'Cross-functional', 'кросс-функциональное взаимодействие', 'кросс-функциональные команды', 'cross-functional teams', 'кросс-функциональный'),
  e('hard', 'Change management', 'управление изменениями', 'трансформация', 'transformation'),
  e('hard', 'Process optimization', 'оптимизация процессов', 'построение процессов', 'процессы', 'processes'),
  e('hard', 'Vendor management', 'работа с подрядчиками', 'подрядчики', 'агентства', 'agencies', 'управление подрядчиками'),
  e('hard', 'Tender management', 'тендеры', 'тендер'),
  e('hard', 'Financial modeling', 'финансовое моделирование', 'финмодель', 'финансовая модель'),
  e('hard', 'Revenue growth', 'рост выручки', 'выручка', 'revenue'),
  e('hard', 'International markets', 'международные рынки', 'выход на новые рынки', 'new markets', 'международный'),
  e('hard', 'Startups', 'стартапы', 'стартап', 'startup', 'венчур', 'venture'),
  e('hard', 'Fundraising', 'привлечение инвестиций', 'инвестиции', 'investors', 'инвесторы'),

  // --- domains ---
  e('domain', 'AdTech', 'адтех', 'рекламные технологии', 'ad tech'),
  e('domain', 'MarTech', 'мартех', 'маркетинговые технологии', 'mar tech'),
  e('domain', 'FinTech', 'финтех', 'финансовые технологии'),
  e('domain', 'SaaS', 'b2b saas', 'saas-продукт', 'subscription'),
  e('domain', 'B2B', 'b2b-сегмент'),
  e('domain', 'B2C', 'b2c-сегмент', 'd2c', 'dtc'),
  e('domain', 'FMCG', 'cpg', 'товары повседневного спроса'),
  e('domain', 'Retail', 'ритейл', 'розница', 'розничная торговля'),
  e('domain', 'Banking', 'банк', 'банки', 'банковский', 'banks'),
  e('domain', 'Telecom', 'телеком', 'телекоммуникации'),
  e('domain', 'EdTech', 'эдтех', 'онлайн-образование'),
  e('domain', 'HealthTech', 'медтех', 'медицина', 'healthcare'),
  e('domain', 'Gaming', 'геймдев', 'игры', 'gamedev'),
  e('domain', 'Mobile apps', 'мобильные приложения', 'mobile', 'мобильное приложение', 'app marketing'),
  e('domain', 'Agency', 'агентство', 'агентский', 'digital-агентство'),
  e('domain', 'AI', 'ии', 'искусственный интеллект', 'artificial intelligence', 'genai', 'generative ai', 'генеративный ии', 'нейросети', 'llm', 'chatgpt'),
  e('domain', 'Automation', 'автоматизация', 'automations', 'no-code', 'low-code'),

  // --- tools ---
  e('tool', 'Google Analytics', 'ga4', 'google analytics 4', 'ga'),
  e('tool', 'Яндекс Метрика', 'яндекс.метрика', 'метрика', 'yandex metrica', 'yandex metrika'),
  e('tool', 'Яндекс Директ', 'яндекс.директ', 'директ', 'yandex direct'),
  e('tool', 'Google Ads', 'adwords', 'google adwords'),
  e('tool', 'Meta Ads', 'facebook ads', 'facebook', 'instagram ads'),
  e('tool', 'VK Ads', 'vk реклама', 'vk', 'вконтакте', 'мой таргет', 'mytarget'),
  e('tool', 'LinkedIn Ads', 'linkedin'),
  e('tool', 'Telegram Ads', 'telegram', 'телеграм'),
  e('tool', 'Google Tag Manager', 'gtm container', 'tag manager'),
  e('tool', 'Amplitude'),
  e('tool', 'Mixpanel'),
  e('tool', 'AppMetrica', 'appsflyer', 'adjust'),
  e('tool', 'Power BI', 'powerbi'),
  e('tool', 'Tableau'),
  e('tool', 'Looker Studio', 'looker', 'google data studio', 'data studio', 'datalens', 'даталенс'),
  e('tool', 'Excel', 'google sheets', 'гугл таблицы', 'спредшиты', 'spreadsheets', 'vba'),
  e('tool', 'SQL', 'postgresql', 'postgres', 'mysql', 'clickhouse', 'bigquery'),
  e('tool', 'Python', 'pandas', 'jupyter'),
  e('tool', 'HubSpot'),
  e('tool', 'Salesforce', 'sfdc'),
  e('tool', 'amoCRM', 'amo crm', 'амо crm'),
  e('tool', 'Bitrix24', 'битрикс24', 'битрикс'),
  e('tool', 'CRM', 'crm-системы', 'crm-система', 'crm системы'),
  e('tool', 'Mindbox'),
  e('tool', 'Unisender', 'sendpulse', 'mailchimp', 'esputnik'),
  e('tool', 'Braze', 'customer.io', 'iterable'),
  e('tool', 'Segment', 'cdp', 'customer data platform'),
  e('tool', 'Marketo', 'pardot'),
  e('tool', 'Jira', 'confluence', 'atlassian'),
  e('tool', 'Notion'),
  e('tool', 'Miro'),
  e('tool', 'Figma'),
  e('tool', 'Tilda', 'тильда'),
  e('tool', 'WordPress'),
  e('tool', 'Webflow'),
  e('tool', 'n8n', 'zapier', 'make.com'),
  e('tool', 'Semrush', 'ahrefs', 'serpstat'),
  e('tool', 'Similarweb'),
  e('tool', 'Calltouch', 'comagic', 'roistat', 'коллтрекинг', 'calltracking'),
  e('tool', 'Hotjar', 'вебвизор'),
  e('tool', 'Optimizely', 'google optimize', 'varioqub'),
  e('tool', 'TypeScript', 'javascript', 'js', 'ts'),
  e('tool', 'React', 'next.js', 'nextjs'),
  e('tool', 'Node.js', 'node', 'express'),
  e('tool', 'Git', 'github', 'gitlab'),
  e('tool', 'API', 'rest api', 'интеграции', 'integrations'),
  e('tool', 'Cursor', 'claude', 'copilot', 'github copilot'),

  // --- soft ---
  e('soft', 'Leadership', 'лидерство', 'лидерские качества'),
  e('soft', 'Communication', 'коммуникация', 'коммуникабельность', 'коммуникативные навыки', 'communication skills'),
  e('soft', 'Ownership', 'ответственность', 'проактивность', 'proactive', 'проактивный', 'accountability'),
  e('soft', 'Analytical thinking', 'аналитическое мышление', 'аналитический склад ума', 'analytical skills', 'analytical mindset'),
  e('soft', 'Structured thinking', 'системное мышление', 'структурное мышление', 'системность', 'systems thinking'),
  e('soft', 'Data-driven', 'data driven', 'управление на основе данных', 'решения на основе данных'),
  e('soft', 'Result orientation', 'ориентация на результат', 'результативность', 'results-oriented', 'result-oriented'),
  e('soft', 'Presentation skills', 'презентации', 'выступления', 'публичные выступления', 'public speaking'),
  e('soft', 'Mentoring', 'менторинг', 'наставничество', 'coaching', 'коучинг', 'развитие команды'),
  e('soft', 'Creativity', 'креативность', 'креатив', 'creative'),
  e('soft', 'Multitasking', 'многозадачность', 'приоритизация', 'prioritization'),
  e('soft', 'English', 'en', 'английский', 'английский язык', 'english b2', 'english c1', 'upper-intermediate', 'advanced english', 'fluent english'),
  e('soft', 'French', 'fr', 'французский', 'французский язык'),
  e('soft', 'Spanish', 'испанский', 'испанский язык'),
];
